require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Rails/FilePath:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - but

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: false


Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  VersionAdded: '0.9'
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
